# Generated by Django 4.0.6 on 2022-07-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='pizza',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza'),
        ),
    ]
