# Generated by Django 4.0.6 on 2022-07-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toppings_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='text',
            new_name='topping',
        ),
    ]
